[package]
name = "bevy_prototype_lyon"
version = "0.1.1"
authors = ["Federico Rinaldi <gisquerin@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Draw 2D shapes and paths in Bevy."
repository = "https://github.com/Nilirad/bevy_prototype_lyon/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.3"
lyon = "0.16.0"